### PR TITLE
feat: ✨ adds UserFollows widget/component

### PR DESCRIPTION
**Pull request by Roaa94**
## Status

**READY**

## Description

* Adds the `UserFollows` widget/component
   * Contains followers & follows count and is going to be used later in the profile page header.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by jenshor — APPROVED** [review]
LGTM 🎉

However, in my opinion, we should create the `TwitterGap` (or however you want to call it) as soon as possible to replace the usage of `SizedBox(width: 5)` and `SizedBox(width: 20)`. Otherwise, it'll be a pain to migrate later.

**Comment by jenshor** [comment]
Oh, and it would be great as well if PRs only have 1 commit (and merges). But you can merge this without fixing it. Just saying it so we have it that way in upcoming PRs 👍🏻

**Comment by Roaa94** [comment]
> Oh, and it would be great as well if PRs only have 1 commit (and merges). But you can merge this without fixing it. Just saying it so we have it that way in upcoming PRs 👍🏻

Just FYI I usually do the 1 commit thing after you review just in case I have to add additional edits and commits. (Also sometimes I forget 😅)

**Comment by jenshor** [comment]
No worries. To hard enforce this in the future, we should also have an action that checks for such a convention. But I think we currently have better things to do 😀

**Pull request merged**
